### ISSUE TITLE
pointnet2_cuda问题

### ISSUE THREAD

**Issue by liyx2001** [PKU-EPIC/HOTrack#7]
pytorch=1.9.1 +CUDA11.1 无法运行，如何适配？
编译pointnet2_cuda时报错。
Traceback (most recent call last):
  File "network/train.py", line 16, in <module>
    from datasets.dataset import get_dataloader
  File "/hy-tmp/HOTrack-main/network/../datasets/dataset.py", line 15, in <module>
    from SimGrasp_dataset import SimGraspDataset
  File "/hy-tmp/HOTrack-main/network/../datasets/SimGrasp_dataset.py", line 8, in <module>
    from network.models.hand_utils import handkp2palmkp
  File "/hy-tmp/HOTrack-main/network/../datasets/../network/models/hand_utils.py", line 3, in <module>
    from pointnet_utils import knn_point, group_operation
  File "/hy-tmp/HOTrack-main/network/../datasets/../network/models/pointnet_utils.py", line 10, in <module>
    from pointnet_lib import pointnet2_utils as futils
  File "/hy-tmp/HOTrack-main/network/../datasets/../network/models/pointnet_lib/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /usr/local/lib/python3.8/dist-packages/pointnet2-0.0.0-py3.8-linux-x86_64.egg/pointnet2_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

**Comment by JYChen18** [comment]
Sorry for the late reply.

It is due to the misalignment between the CUDA you use to compile the lib and the CUDA you use to run. 

You may need to change the environment variable $CUDA_HOME to point to a system CUDA with version 11.x, and recompile the pointnet2. Or change the pytorch version.

Please also see #5 .
